"""create telemetry_events and copilot_runs

Revision ID: df4c00817db4
Revises: 
Create Date: 2026-01-07 22:15:22.097502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4c00817db4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_runs_id'), 'copilot_runs', ['id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('packet_loss', sa.Integer(), nullable=False),
    sa.Column('audio_dropouts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_device_id'), 'telemetry_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_id'), 'telemetry_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_events_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_device_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_copilot_runs_id'), table_name='copilot_runs')
    op.drop_table('copilot_runs')
    # ### end Alembic commands ###
